services:
  - type: web
    plan: free
    name: URL-UPLOADER
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 bot.py
    repo: https://github.com/EliteCraftStudios/URL-UPLOADER.git
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      - key: UPDATES_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: true
      - key: DATABASE_URL
        sync: true
      - key: BOT_USERNAME
        sync: true
      - key: OWNER_ID
        sync: true
      - key: WEBHOOK
        sync: false
